### ISSUE TITLE
关于中断训练之后继续训练的问题

### ISSUE THREAD

**Issue by Video54367** [csguoh/LEMMA#10]
请问一下代码中的resume是只能test的时候使用吗？继续训练时如何加载已经保存好的权重？我观察到训练产生的权重文件有两个，checkpoint.pth和model_best_acc_0.pth，继续训练时需要用哪个权重？

**Comment by csguoh** [comment]
你好，`checkpoint.pth`存放的是最近一个epoch的权重，`model_best_acc_0.pth`存放的是当前效果最好的模型权重。如果想要断点训练，可以使用`checkpoint.pth`来加载模型。
