### ISSUE TITLE
关于生成单张图片SR的问题

### ISSUE THREAD

**Issue by ych-tju** [csguoh/LEMMA#12]
您好，请问如何实现生成指定的单张SR图像呢？
还有我想请问一下论文当中的Attention Map Sequence的可视化图是如何得到的？
谢谢！

**Comment by csguoh** [comment]
您好，
如果想要使用指定图片进行超分辨率，可以修改原始test函数里的dataloader代码。
注意力图序列可以在[这个函数](https://github.com/csguoh/LEMMA/blob/ad25df9c71229ad6b5ac8d05e0bbce7e50940701/model/Position_aware_module.py#L254)的输出中得到。

**Comment by erenxjw** [comment]
> 您好， 如果想要使用指定图片进行超分辨率，可以修改原始test函数里的dataloader代码。 注意力图序列可以在[这个函数](https://github.com/csguoh/LEMMA/blob/ad25df9c71229ad6b5ac8d05e0bbce7e50940701/model/Position_aware_module.py#L254)的输出中得到。

您好，十分抱歉，我按照您提示的修改原始test函数，但由于能力原因没能实现使用指定图片进行超分辨率，麻烦您能再给予一些提示，我将感激不尽！
