### ISSUE TITLE
关于输出字体变色问题

### ISSUE THREAD

**Issue by kwan-ma** [csguoh/LEMMA#13]
![17066959471483](https://github.com/csguoh/LEMMA/assets/84896234/e4396d9f-156b-4b7a-9bf9-5b5edc21c391)
您好，我在测试算法的时候，随机测试了一些真实场景，得到了异样的结果，出现在一小部分图片中，看起来像是色值溢出，但读图时使用了。我是直接在lemma.py代码里面读入真实图。

**Comment by csguoh** [comment]
您好，
如果存在色值溢出的问题，可以在模型的最终输出后加上clip函数，例如`np.clip(sr_img,0,255)`. 另外，如果特定任务训练数据集充裕的话，可以再在特定任务上微调以更好的提升效果。
