### ISSUE TITLE
代码修改

### ISSUE THREAD

**Issue by chengrose1** [csguoh/LEMMA#15]
你好，诚挚的想问一下作者第一次和第二次的代码调整了哪些啊，想学习一下解决问题的方法，还有就是这个代码就是后一次训练的代码嘛

**Comment by csguoh** [comment]
感谢您对我们工作的关注！
我们没有对代码进行修改，如果想要查看具体修改内容的话，可以看一下仓库commit的提交记录，里面会有详细的修改前后对照。目前开源的代码就是我们方法的最终版本。
