### ISSUE TITLE
如何用jpg等图片格式做测试

### ISSUE THREAD

**Issue by meihao5631** [csguoh/LEMMA#16]
作者您好，看到您代码里的测试数据是mdb格式，想请问一下如何用图片格式进行测试呢，期待回复，多谢多谢

**Comment by csguoh** [comment]
这个可以修改dataloader函数，直接在__getitem__里读取jpg图片之后返回即可。

**Comment by Bhavik-Ardeshna** [comment]
@meihao5631 Hi, I am also trying to convert the mdb format to jpg images for testing the model. I am wondering if you are able to implement the changes that can accept jpg images.

I need some help in that part. Thank you.

**Comment by csguoh** [comment]
You need to modify the dataloader function to allow the reading of images of other format. This is not hard, you can achieve this by yourself.
