### ISSUE TITLE
stn操作

### ISSUE THREAD

**Issue by FocueAI** [csguoh/LEMMA#21]
为什么只在训练的时候才考虑使用tps？
![image](https://github.com/csguoh/LEMMA/assets/49752023/a78c478e-66b3-4b87-a748-0618f04235b4)

**Comment by csguoh** [comment]
Hi, 
The TPS is indeed used only during training, which is also a common practice in previous work. We also tested using TPS in the testing, but it does bring much performance improvement.

**Comment by FocueAI** [comment]
1. 是否做过在训练中也不加TPS的效果呢？
2. 是否可以解释下，TPS在测试中不能带来好的表现的原因呢？
期待您的解答，谢谢了

**Comment by csguoh** [comment]
Hi, 
1. Since the TextZoom is collected with real-world dual-zoom camera, it is necessary to calibrate with STN
2. Using STN in testing does not lead to sever performance drop.  Probably the testing gap, testing and training do not share the same pixel shit, be the reason.
