### ISSUE TITLE
ABINet of LEMMA

### ISSUE THREAD

**Issue by 2061360308** [csguoh/LEMMA#24]
Does LEMMA necessarily require ABiNet to provide text attention? If I retrain ABiNet, can it significantly improve the performance of LEMMA.

The following is the output result after 60 rounds of training. Compared to the input image, the output image is much blurry. Is this normal? My configuration was completely based on the default parameters, and the test model used the default CRNN

![9c048ad30a1b3ff0fd0f88b37f8c2297](https://github.com/user-attachments/assets/1b13f3c5-5f16-45a3-b81a-a599caddba8b)

**Comment by csguoh** [comment]
Theoretically, any attention-based OCR model is fine to be intergrated into LEMMA to offer the spatial position prior. The ABINet is also fine-tuned during the training process of LEMMA. If you have followed the exact same config, the output of LEMMA model should not appears like that, we have checked the repo when we release the code. Maybe there is some bug of your code.

**Comment by 2061360308** [comment]
> Theoretically, any attention-based OCR model is fine to be intergrated into LEMMA to offer the spatial position prior. The ABINet is also fine-tuned during the training process of LEMMA. If you have followed the exact same config, the output of LEMMA model should not appears like that, we have checked the repo when we release the code. Maybe there is some bug of your code.

Thank you for your explanation. I will review my code again.
