### ISSUE TITLE
关于demo

### ISSUE THREAD

**Issue by wu-yz** [csguoh/LEMMA#4]
您好！请问有没有demo能看看效果呀?

**Comment by csguoh** [comment]
你好，感谢您对我们工作的关注。
我们在论文中给出了超分后的一些样例，您可以看一下文章中的Fig.4或者[这里](https://github.com/csguoh/LEMMA#qualitative-comparison)。
另外您也可以下载预训练模型，运行`python main.py --test`并存储模型的超分输出结果来查看更多样例。
由于时间关系，目前我们并没有开发交互式界面。
