### ISSUE TITLE
where can I get the pretrain_transformer.pth

### ISSUE THREAD

**Issue by Video54367** [csguoh/LEMMA#5]
Hello，Thanks for your work. I thoroughly enjoyed reading the paper ,Your code is so perfect and I just want to know how can I get the pretrain_transformer.pth?

**Comment by csguoh** [comment]
Thanks for your interest of our work.
You can download the ckpt of the pretrain_transformer with [this](https://drive.google.com/file/d/1HRpzveBbnJPQn3-k_y2Y1YY4PcraWOFP/view?usp=drive_link) link.
