### ISSUE TITLE
请问可以提供关于pretrain-language-model.pth吗或者从哪里下载呢

### ISSUE THREAD

**Issue by llvhjgtdl** [csguoh/LEMMA#6]

**Comment by csguoh** [comment]
Hi, thanks for your attention for our work.
One can download the 'pretrain-language-model.pth' with [this link](https://drive.google.com/file/d/1UNIUEae0Uty1Gllriandxa3rokSPmS2u/view?usp=sharing).
Please let me know if you have any other question.

**Comment by llvhjgtdl** [comment]
感谢您的回复，我是想在我的代码中也使用这个预训练的language-model，想请问是在配置文件中添加language-model的相关信息，然后self.language = BCNLanguage(config)就能调用预训练模型嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hang ***@***.***&gt;; 
发送时间: 2023年12月16日(星期六) 上午9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [csguoh/LEMMA] 请问可以提供关于pretrain-language-model.pth吗或者从哪里下载呢 (Issue #6)





 
Hi, thanks for your attention for our work.
 One can download the 'pretrain-language-model.pth' with this link.
 Please let me know if you have any other question.

**Comment by csguoh** [comment]
是的

**Comment by llvhjgtdl** [comment]
> 是的

非常感谢，请问您能提供这篇代码的预训练模型吗

**Comment by csguoh** [comment]
You can download the pre-trained language model with the above reply. 
The pre-trained weight of LEMMA can be found in README.md

**Comment by llvhjgtdl** [comment]
非常感谢，您每次回复的都很及时




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csguoh/LEMMA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 中午11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csguoh/LEMMA] 请问可以提供关于pretrain-language-model.pth吗或者从哪里下载呢 (Issue #6)





 
You can download the pre-trained language model with the above reply.
 The pre-trained weight of LEMMA can be found in README.md
