### ISSUE TITLE
请问怎么得到可视化SR图像呢

### ISSUE THREAD

**Issue by llvhjgtdl** [csguoh/LEMMA#9]
我观察TATT是再super-resolition.pywen文件中修改vis=true即可得可视化的SR图像，请问您的代码里相关的再哪里呢？
![image](https://github.com/csguoh/LEMMA/assets/146192179/4abe6847-666e-4d5e-8eba-a777851215ec)
ling'w另外请问这个超分出来的图片怎么得到识别出的字符呢？

**Comment by csguoh** [comment]
你好，感谢对我们工作的关注。
如果您想要存下超分后的结果，可以在main函数里选择test模式，同时在[这一行](https://github.com/csguoh/LEMMA/blob/ad25df9c71229ad6b5ac8d05e0bbce7e50940701/interfaces/super_resolution.py#L282C18-L282C18)之后添加存储image_sr的代码。此外[这一行](https://github.com/csguoh/LEMMA/blob/ad25df9c71229ad6b5ac8d05e0bbce7e50940701/interfaces/super_resolution.py#L350)的`predict_result_sr`变量会存储一个批次的SR文本识别结果。

**Comment by llvhjgtdl** [comment]
> 你好，感谢对我们工作的关注。 如果您想要存下超分后的结果，可以在main函数里选择test模式，同时在[这一行](https://github.com/csguoh/LEMMA/blob/ad25df9c71229ad6b5ac8d05e0bbce7e50940701/interfaces/super_resolution.py#L282C18-L282C18)之后添加存储image_sr的代码。此外[这一行](https://github.com/csguoh/LEMMA/blob/ad25df9c71229ad6b5ac8d05e0bbce7e50940701/interfaces/super_resolution.py#L350)的`predict_result_sr`变量会存储一个批次的SR文本识别结果。

可以具体告知添加存储image_sr的代码吗，尝试了但是报错

**Comment by csguoh** [comment]
具体是报的什么错呢？

**Comment by meihao5631** [comment]
> > 你好，感谢我们工作的关注。如果您想要存下超分后的结果，可以在主函数里选择test模式，同时在[此行](https://github.com/csguoh/LEMMA/blob/ad25df9c71229ad6b5ac8d05e0bbce7e50940701/interfaces/super_resolution.py#L282C18-L282C18)之后添加存储image_sr的代码。此外，[这一行](https://github.com/csguoh/LEMMA/blob/ad25df9c71229ad6b5ac8d05e0bbce7e50940701/interfaces/super_resolution.py#L350)的`predict_result_sr`变量会存储一个批量的 SR 文本识别结果。
> 
> 可以具体告知添加存储image_sr的代码吗，尝试了但是报错

你好，请问您这个问题解决了吗，我也遇到了同样的问题
